# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  iosevka = {
    pname = "iosevka";
    version = "v16.3.3";
    src = fetchFromGitHub ({
      owner = "be5invis";
      repo = "Iosevka";
      rev = "v16.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-AdkRlkKZunplPGXdl/UbSZi7gMHceHRXM3XDMwLMvEA=";
    });
  };
}
